[project]
name = "bit-share"
version = "0.1.0"
description = "Simple Torrent Like service to share files in the local network"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.2.2",
]

[project.scripts]
"bit-share" = "bit_share.__main__:main"
